#!/usr/bin/env perl
#
use strict;
use warnings;
use Getopt::Long;
use Time::HiRes qw(gettimeofday);

# riboscan :: scan sequences against Ribovore model libraries
# Usage: riboscan [-options] <fasta file to annotate> <output directory>

require "ribo.pm";

# make sure required environment variables are set
my $env_ribo_install_dir  = utl_DirEnvVarValid("RIBOINSTALLDIR");
my $env_riboscripts_dir   = utl_DirEnvVarValid("RIBOSCRIPTSDIR");
my $env_ribo_config_file  = (exists $ENV{"RIBOCONFIGFILE"}) ? $ENV{"RIBOCONFIGFILE"} : undef;

my %execs_H = (); # hash with paths to all required executables
$execs_H{"ribotyper"}    = $env_riboscripts_dir  . "/ribotyper";

# deal with 'time' differently because we can deal if it doesn't exist and
# we only use it if it does exist and -p is used
my $env_ribotime_dir = ribo_CheckForTimeExecutable(); # this will return undef if time doesn't exist or is undef
if(defined $env_ribotime_dir) {
  $execs_H{"time"} = $env_ribotime_dir . "/time";
}

#########################################################
# Command line and option processing using sqp_opts.pm
#
# opt_HH: 2D hash:
#         1D key: option name (e.g. "-h")
#         2D key: string denoting type of information 
#                 (one of "type", "default", "group", "requires", "incompatible", "preamble", "help")
#         value:  string explaining 2D key:
#                 "type":         "boolean", "string", "integer" or "real"
#                 "default":      default value for option
#                 "group":        integer denoting group number this option belongs to
#                 "requires":     string of 0 or more other options this option requires to work, each separated by a ','
#                 "incompatible": string of 0 or more other options this option is incompatible with, each separated by a ','
#                 "preamble":     string describing option for preamble section (beginning of output from script)
#                 "help":         string describing option for help section (printed if -h used)
#                 "setby":        '1' if option set by user, else 'undef'
#                 "value":        value for option, can be undef if default is undef
#
# opt_order_A: array of options in the order they should be processed
# 
# opt_group_desc_H: key: group number (integer), value: description of group for help output
my %opt_HH = ();      
my @opt_order_A = (); 
my %opt_group_desc_H = ();
my $g = 0; # option group

# Add all options to %opt_HH and @opt_order_A.
# This section needs to be kept in sync (manually) with the &GetOptions call below

$opt_group_desc_H{++$g} = "basic options";
#     option            type       default               group   requires incompat    preamble-output                                               help-output    
opt_Add("-h",           "boolean", 0,                        0,    undef, undef,      undef,                                                        "display this help",                                  \%opt_HH, \@opt_order_A);
opt_Add("-f",           "boolean", 0,                       $g,    undef, undef,      "forcing directory overwrite",                                "force; if <output directory> exists, overwrite it",  \%opt_HH, \@opt_order_A);
opt_Add("-v",           "boolean", 0,                       $g,    undef, undef,      "be verbose",                                                 "be verbose; output commands to stdout as they're run", \%opt_HH, \@opt_order_A);
opt_Add("-c",           "string",  0,                       $g,    undef, undef,      "use config file <s> instead of default in \$RIBOCONFIGFILE", "use config file <s> instead of default in \$RIBOCONFIGFILE", \%opt_HH, \@opt_order_A);
opt_Add("--keep",       "boolean", 0,                       $g,    undef, undef,      "keep all intermediate files",                                "keep all intermediate files that are removed by default", \%opt_HH, \@opt_order_A);

# This section needs to be kept in sync (manually) with the opt_Add() section above
my %GetOptions_H = ();
my $usage    = "Usage: riboscan [-options] <fasta file to annotate> <output directory>\n";
my $synopsis = "riboscan :: scan sequences against Ribovore model libraries";
my $options_okay = 
    &GetOptions('h'            => \$GetOptions_H{"-h"}, 
                'f'            => \$GetOptions_H{"-f"},
                'v'            => \$GetOptions_H{"-v"},
                'c=s'          => \$GetOptions_H{"-c"},
                'keep'         => \$GetOptions_H{"--keep"});

my $total_seconds     = -1 * ofile_SecondsSinceEpoch(); # by multiplying by -1, we can just add another ofile_SecondsSinceEpoch call at end to get total time
my $executable        = $0;
my $date              = scalar localtime();
my $version           = "1.1dev";
my $releasedate       = "Mar 2025";
my $package_name      = "Ribovore";

# make *STDOUT file handle 'hot' so it automatically flushes whenever we print to it
select *STDOUT;
$| = 1;

# print help and exit if necessary
if((! $options_okay) || ($GetOptions_H{"-h"})) { 
  ofile_OutputBanner(*STDOUT, $package_name, $version, $releasedate, $synopsis, $date, undef);
  opt_OutputHelp(*STDOUT, $usage, \%opt_HH, \@opt_order_A, \%opt_group_desc_H);
  if(! $options_okay) { die "ERROR, unrecognized option;"; }
  else                { exit 0; } # -h, exit with 0 status
}

# check that number of command line args is correct
if(scalar(@ARGV) != 2) {   
  print "Incorrect number of command line arguments.\n";
  print $usage;
  print "\nTo see more help on available options, enter 'riboscan -h'\n\n";
  exit(1);
}
my ($seq_file, $dir_out) = (@ARGV);

# set options in opt_HH
opt_SetFromUserHash(\%GetOptions_H, \%opt_HH);

# validate options (check for conflicts)
opt_ValidateSet(\%opt_HH, \@opt_order_A);

utl_ExecHValidate(\%execs_H, undef);

my $cmd         = undef; # a command to be run by utl_RunCommand()
my @early_cmd_A = (); # array of commands we run before our log file is opened
my @to_remove_A = ();    # array of files to remove at end

# if $dir_out already exists remove it only if -f also used
if(-d $dir_out) { 
  $cmd = "rm -rf $dir_out";
  if(opt_Get("-f", \%opt_HH)) { utl_RunCommand($cmd, opt_Get("-v", \%opt_HH), 0, undef); push(@early_cmd_A, $cmd); }
  else                        { die "ERROR intended output directory named $dir_out already exists. Remove it, or use -f to overwrite it."; }
}
elsif(-e $dir_out) { 
  $cmd = "rm $dir_out";
  if(opt_Get("-f", \%opt_HH)) { utl_RunCommand($cmd, opt_Get("-v", \%opt_HH), 0, undef); push(@early_cmd_A, $cmd); }
  else                        { die "ERROR a file matching the name of the intended output directory $dir_out already exists. Remove the file, or use -f to overwrite it."; }
}
# if $dir_out does not exist, create it
if(! -d $dir_out) { 
  $cmd = "mkdir $dir_out";
  utl_RunCommand($cmd, opt_Get("-v", \%opt_HH), 0, undef); push(@early_cmd_A, $cmd); 
}

my $dir_out_tail = $dir_out;
$dir_out_tail    =~ s/^.+\///; # remove all but last dir
my $out_root     = $dir_out .   "/" . $dir_out_tail   . ".ribotyper";



#############################################
# output program banner and open output files
#############################################
# output preamble
my @arg_desc_A = ();
my @arg_A      = ();

push(@arg_desc_A, "target sequence input file");
push(@arg_A, $seq_file);

push(@arg_desc_A, "output directory name");
push(@arg_A, $dir_out);

my %extra_H    = ();
$extra_H{"\$RIBOSCRIPTSDIR"} = $env_riboscripts_dir;
if(defined $env_ribo_config_file) { 
  $extra_H{"\$RIBOCONFIGFILE"} = $env_ribo_config_file;
}
if(defined $env_ribotime_dir) { 
  $extra_H{"\$RIBOTIMEDIR"} = $env_ribotime_dir;
}
ofile_OutputBanner(*STDOUT, $package_name, $version, $releasedate, $synopsis, $date, \%extra_H);
opt_OutputPreamble(*STDOUT, \@arg_desc_A, \@arg_A, \%opt_HH, \@opt_order_A);

# open the log and command files:
# set output file names and file handles, and open those file handles
my %ofile_info_HH = ();  # hash of information on output files we created,
                         # 1D keys: 
                         #  "fullpath":  full path to the file
                         #  "nodirpath": file name, full path minus all directories
                         #  "desc":      short description of the file
                         #  "FH":        file handle to output to for this file, maybe undef
                         # 2D keys:
                         #  "log": log file of what's output to stdout
                         #  "cmd": command file with list of all commands executed

# open the list, log and command files 
ofile_OpenAndAddFileToOutputInfo(\%ofile_info_HH, "list", $out_root . ".list", 1, 1, "List and description of all output files");
ofile_OpenAndAddFileToOutputInfo(\%ofile_info_HH, "log",  $out_root . ".log",  1, 1, "Output printed to screen");
ofile_OpenAndAddFileToOutputInfo(\%ofile_info_HH, "cmd",  $out_root . ".cmd",  1, 1, "List of executed commands");
my $log_FH = $ofile_info_HH{"FH"}{"log"};
my $cmd_FH = $ofile_info_HH{"FH"}{"cmd"};
# output files are all open, if we exit after this point, we'll need
# to close these first.

# now we have the log file open, output the banner there too
ofile_OutputBanner($log_FH, $package_name, $version, $releasedate, $synopsis, $date, \%extra_H);
opt_OutputPreamble($log_FH, \@arg_desc_A, \@arg_A, \%opt_HH, \@opt_order_A);

# output any commands we already executed to $log_FH
foreach $cmd (@early_cmd_A) { 
  print $cmd_FH $cmd . "\n";
}

my $progress_w = 68; # the width of the left hand column in our progress output, hard-coded
my $start_secs = ofile_OutputProgressPrior("Validating input files", $progress_w, $log_FH, *STDOUT);

# verify the fasta file exists
utl_FileValidateExistsAndNonEmpty($seq_file, "sequence file", undef, 1, $ofile_info_HH{"FH"}); # '1' says: die if it doesn't exist or is empty

# parse the ribo config file
my $config_file = $env_ribo_config_file; # this may be undef
if(opt_IsUsed("-c", \%opt_HH)) {
  $config_file = opt_Get("-c", \%opt_HH);
  utl_FileValidateExistsAndNonEmpty($config_file, "config file specified with -c", undef, 1, undef); # '1' says: die if it doesn't exist or is empty
}
else {
  if(! defined $config_file) {
    die "\nERROR, the environment variable \$RIBOCONFIGFILE is not set,\neither set it as the path to the riboscan config file or use the -c option\n";
  }
  utl_FileValidateExistsAndNonEmpty($config_file, "config file defined by env variable \$RIBOCONFIGFILE", undef, 1, undef); # '1' says: die if it doesn't exist or is empty
}
my @lkey_A      = ();
my %lkey_ldir_H = ();
my %lkey_opts_H = ();
my %lkey_info_H = ();
parse_config_file($config_file, $env_ribo_install_dir, \@lkey_A, \%lkey_ldir_H, \%lkey_opts_H, \%lkey_info_H, \%opt_HH, undef);
ofile_OutputProgressComplete($start_secs, undef, $log_FH, *STDOUT);

# run ribotyper for each library
my $lkey;
foreach $lkey (@lkey_A) {
  my $ribotyper_dir_out    = $dir_out . "/" . $dir_out_tail . "." . $lkey;
  my $ribotyper_stdoutfile = $dir_out . "/" . $dir_out_tail . "." . $lkey . ".out";
  my $ribotyper_cmd        = $execs_H{"ribotyper"} . " -m " . $lkey_ldir_H{$lkey} . " -i " . $lkey_info_H{$lkey} . " $seq_file $ribotyper_dir_out > $ribotyper_stdoutfile";
  my $ribotyper_secs       = 0.; # total number of seconds elapsed for ribotyper stage
  my $ribotyper_longfile   = $ribotyper_dir_out . "/" . $dir_out_tail . "." . $lkey . ".ribotyper.long.out";
  my $ribotyper_logfile    = $ribotyper_dir_out . "/" . $dir_out_tail . "." . $lkey . ".ribotyper.log";
  $start_secs = ofile_OutputProgressPrior("Running ribotyper for library $lkey on full sequence file", $progress_w, $log_FH, *STDOUT);
  utl_RunCommand($ribotyper_cmd, opt_Get("-v", \%opt_HH), 0, $ofile_info_HH{"FH"});
  $ribotyper_secs = ofile_OutputProgressComplete($start_secs, undef, $log_FH, *STDOUT);
}

##########
# Conclude
##########
# remove files we don't want anymore, then exit
foreach my $file (@to_remove_A) { 
  unlink $file;
}

$total_seconds += ofile_SecondsSinceEpoch();

ofile_OutputConclusionAndCloseFilesOk($total_seconds, $dir_out, \%ofile_info_HH);
exit(0); 

###########################################################################

#####################################################################
# SUBROUTINES 
#####################################################################
#################################################################
# Subroutine: parse_config_file
# Incept:     EPN, Tue Mar 25 10:54:01 2025
# 
# Purpose:    Parse the special riboscan config file and store
#             the relevant info in 
# Arguments:
#  $config_file:          path to config file
#  $env_ribo_install_dir: path to replace $RIBOINSTALLDIR with, can be undef (in which case we don't replace it)
#  $lkey_AR:              REF to array of library keys
#  $lkey_ldir_HR:         REF to hash, key is lkey, value is library directory for this lkey, filled here
#  $lkey_opts_HR:         REF to hash, key is lkey, value is options string to use with ribotyper for this lkey, filled here
#  $lkey_info_HR:         REF to hash, key is lkey, value is modelinfo to use with ribotyper for this lkey, filled here
#  $opt_HHR:              REF to 2D hash of option values, see top of sqp_opts.pm for description
#  $FH_HR:                REF to hash of file handles
#
# Returns:  void
#           
# Dies:     if problem parsing config file
#
#################################################################
sub parse_config_file { 
  my $sub_name = "parse_config_file"; 
  my $nargs_exp = 8;
  if(scalar(@_) != $nargs_exp) { die "ERROR $sub_name entered with wrong number of input args"; }

  my ($config_file, $env_ribo_install_dir, $lkey_AR, $lkey_ldir_HR, $lkey_opts_HR, $lkey_info_HR, $opt_HHR, $FH_HR) = (@_);

  open(CONFIG, $config_file) || ofile_FileOpenFailure($config_file, $sub_name, $!, "reading", $FH_HR);

  my $line;
  my ($lkey, $ldir, $opts);
  while($line = <CONFIG>) {
    chomp $line;
    if(($line =~ m/\w/) && ($line !~ m/^\#/)) {
      my @el_A = split(/\s+/, $line);
      if(scalar(@el_A) < 2) {
        ofile_FAIL("ERROR, all non-comment lines should include at least two white space delimited fields: <outkey> <modeldir>\nread line:\n$line", 1, $FH_HR);
      }
      my ($lkey, $ldir) = ($el_A[0], $el_A[1]);
      if(defined $env_ribo_install_dir) { # replace $RIBOINSTALLDIR with passed in $env_vadr_install_dir (if defined)
        $ldir =~ s/\$RIBOINSTALLDIR/$env_ribo_install_dir/g;
      }
      my $opts = "";
      for(my $i = 2; $i < scalar(@el_A); $i++) {
        if($opts ne "") { $opts .= " "; }
        $opts .= $el_A[$i];
      }
      if(defined $lkey_ldir_H{$lkey}) {
        ofile_FAIL("ERROR read library model key $lkey twice in config file", 1, $FH_HR);
      }
      push(@{$lkey_AR}, $lkey);
      $lkey_ldir_HR->{$lkey} = $ldir;
      $lkey_opts_HR->{$lkey} = $opts;
      $lkey_info_HR->{$lkey} = $ldir . "/" . $lkey . ".modelinfo";

      # make sure $ldir is a valid dir, and $ldir/$lkey.modelinfo exists
      if(! (-d $ldir)) { 
        ofile_FAIL("ERROR, library directory $ldir listed in $config_file does not exist", 1, $FH_HR);
      }
      if(! (-s "$lkey_info_HR->{$lkey}")) { 
        ofile_FAIL("ERROR, when validating $config_file: required modelinfo file $lkey_info_HR->{$lkey} does not exist", 1, $FH_HR);
      }
    }
  }
  close(CONFIG);

  return;
}
